# Dependencies
markdown:         kramdown 

gems: [jekyll-paginate]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Jonas Karlsson 
tagline:          'Hacker extraordinaire'
description:      'Hacker extraordinaire from Sweden.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jonas Karlsson'
  url:            https://twitter.com/jonas_rofl

paginate:         5

github:
  repo:           https://github.com/poole/hyde

kramdown:
  input: GFM
  syntax_highlighter: rouge
